import re

import yaml


def _load_type_map(type_map_path: str = "tool/config/type_map.yaml") -> tuple:
    with open(type_map_path) as f:
        data = yaml.safe_load(f)
    return data.get("type_mappings", {}), set(data.get("ambiguous_mappings", []))


def _map_type(sql_type: str, type_mappings: dict, ambiguous: set) -> str:
    upper = sql_type.strip().upper()
    # Check ambiguous first (exact or prefix match)
    for amb in ambiguous:
        if upper == amb.upper() or upper.startswith(amb.upper().split("(")[0] + "(MAX)"):
            return f"{sql_type}  -- [VERIFY TYPE: maps to TEXT, confirm no length constraint]"
    # Strip length specifier for lookup, preserve it in output
    base = re.split(r"[\s(]", upper)[0]
    mapped = type_mappings.get(base)
    if mapped:
        # If original had length/precision, keep it unless base type changes
        if base in ("DECIMAL", "NUMERIC", "CHAR", "NCHAR") and "(" in sql_type:
            precision = sql_type[sql_type.index("(") :]
            return f"{mapped}{precision}"
        return mapped
    return f"{sql_type}  -- [VERIFY TYPE: unknown SQL Server type]"


class AuroraDDLGenerator:
    AUDIT_TABLES = """
CREATE TABLE IF NOT EXISTS audit.phase1_load (
    run_id              UUID,
    source_name         TEXT,
    table_name          TEXT,
    row_count           BIGINT,
    load_duration_ms    BIGINT,
    loaded_at           TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit.sp_execution_log (
    run_id                  UUID,
    sp_name                 TEXT,
    rows_affected           BIGINT,
    execution_duration_ms   BIGINT,
    executed_at             TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit.phase3_load (
    run_id          UUID,
    target_table    TEXT,
    rows_inserted   BIGINT,
    rows_updated    BIGINT,
    rows_deleted    BIGINT,
    load_duration_ms BIGINT,
    loaded_at       TIMESTAMP DEFAULT now()
);
""".strip()

    def __init__(self, type_map_path: str = "tool/config/type_map.yaml"):
        self.type_mappings, self.ambiguous = _load_type_map(type_map_path)

    def generate(self, context: dict) -> dict:
        """Generate Flyway DDL. Returns {filename: sql_content}."""
        job_name = context["job_name"]
        version = context.get("flyway_version", "V001")
        staging_tables = context.get("staging_tables", [])

        lines = [
            f"-- Flyway DDL migration: {version}__{job_name}.sql",
            "-- Generated by ETL Migration Tool",
            "",
            "CREATE SCHEMA IF NOT EXISTS staging;",
            "CREATE SCHEMA IF NOT EXISTS audit;",
            "",
        ]

        for tbl in staging_tables:
            table_name = tbl if isinstance(tbl, str) else tbl.get("table_name", "")
            columns = [] if isinstance(tbl, str) else tbl.get("columns", [])
            lines.append(f"CREATE UNLOGGED TABLE IF NOT EXISTS {table_name} (")
            col_lines = []
            for col in columns:
                name = col["name"]
                raw_type = col.get("sql_type", "TEXT")
                pg_type = _map_type(raw_type, self.type_mappings, self.ambiguous)
                nullable = "" if col.get("nullable", True) else " NOT NULL"
                col_lines.append(f"    {name:<30} {pg_type}{nullable}")
            if not col_lines:
                col_lines = ["    _batch_id   BIGSERIAL", "    _loaded_at  TIMESTAMP DEFAULT now()"]
            lines.append(",\n".join(col_lines))
            lines.append(");\n")

        lines.append(self.AUDIT_TABLES)

        sql = "\n".join(lines)
        filename = f"db-migrations/{version}__{job_name}.sql"
        return {filename: sql}
